Update codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -55,6 +55,12 @@ workflows:
           EOF
           /usr/bin/plutil -replace com.apple.developer.aps-environment -string production ios/App/App/App.entitlements
           sed -i '' 's/CODE_SIGN_ENTITLEMENTS = /CODE_SIGN_ENTITLEMENTS = App\/App.entitlements; \/\/ /g' ios/App/App.xcodeproj/project.pbxproj
+          - name: Debug Entitlements
+        script: |
+          echo "=== ENTITLEMENTS FILE ===" 
+          cat ios/App/App/App.entitlements
+          echo "=== PBXPROJ CODESIGN CHECK ==="
+          grep -n "CODE_SIGN_ENTITLEMENTS" ios/App/App.xcodeproj/project.pbxproj || echo "NOT FOUND"
       - name: Install CocoaPods
         script: |
           cd ios/App
